-- AY 2025-26-2
DROP TABLE customer;

CREATE TABLE customer(
  customer_id SMALLINT(3) PRIMARY KEY, 
  first_name VARCHAR(50), 
  last_name VARCHAR(50), 
  gender VARCHAR(15), 
  email VARCHAR(50), 
  city VARCHAR(50), 
  country VARCHAR(50)
);

INSERT INTO customer VALUES
(1, 'Juan', 'Santos', 'Male', 'juan.santos1234@gmail.com', 'Manila', 'Philippines'),
(2, 'Maria', 'Gonzales', 'Female', 'maria.gonzales5678@yahoo.com', 'Quezon City', 'Philippines'),
(3, 'Antonio', 'Cruz', 'Male', 'antonio.cruz9012@hotmail.com', 'Iloilo City', 'Philippines'),
(4, 'Luzviminda', 'Lopez', 'Female', 'luzviminda.lopez3456@outlook.com', 'Manila', 'Philippines'),
(5, 'Crisanto', 'Garcia', 'Male', 'crisanto.garcia7890@gmx.com', 'San Juan', 'Philippines'),
(6, 'Angelo', 'Santos', 'Male', 'asanto123@yahoo.com', 'Pasig', 'Philippines'),
(7, 'Marie', 'Reyes', 'Female', 'marie.reyes89@gmail.com', 'Iloilo City', 'Philippines'),
(8, 'Ricardo', 'Ramos', 'Male', 'rickyramos21@hotmail.com', 'Taguig', 'Philippines'),
(9, 'Tara', 'Salcedo', 'Female', 'salcedo.tara1980@gmail.com', 'San Juan', 'Philippines'),
(10, 'Christian', 'Garcia', 'Male', 'cgarcia22@yahoo.com', 'Manila', 'Philippines'),
(11, 'Jazz', 'Diaz', 'Non-binary', 'jazzydiaz15@gmail.com', 'Pasig', 'Philippines'),
(12, 'Joaquin', 'Santos', 'Male', 'jsantos_10@hotmail.com', 'Naga', 'Philippines'),
(13, 'Bianca', 'Cruz', 'Female', 'biancruz@gmail.com', 'Mandaluyong', 'Philippines'),
(14, 'Raymund', 'Muncal', 'Male', 'raymund.g.muncalIII@yahoo.com', 'Quezon City', 'Philippines'),
(15, 'Sophia', 'Santiago', 'Female', 'ssantiago13@gmail.com', 'Pasig', 'Philippines'),
(16, 'Eduardo', 'Torres', 'Male', 'etorres33@gmail.com', 'San Juan', 'Philippines'),
(17, 'Daniella', 'Gonzales', 'Non-binary', 'dgonzales22@hotmail.com', 'Makati', 'Philippines'),
(18, 'Joel', 'Lopez', 'Male', 'joellopez@gmail.com', 'Taguig', 'Philippines'),
(19, 'Cristina', 'Gomez', 'Female', 'cristinagomez78@yahoo.com', 'Quezon City', 'Philippines'),
(20, 'Juan', 'Luna', 'Male', 'jluna@yahoo.com', 'Pasig', 'Philippines'),
(21, 'Chloe', 'Reyes', 'Female', 'chloereyes01@hotmail.com', 'Makati', 'Philippines'),
(22, 'Luis', 'Gonzales', 'Male', 'luisgonzales@gmail.com', 'Makati', 'Philippines'),
(23, 'Katherine', 'Perez', 'Female', 'kperez_09@yahoo.com', 'Pasig', 'Philippines'),
(24, 'Javier', 'Santos', 'Male', 'j.santos14@gmail.com', 'Mandaluyong', 'Philippines'),
(25, 'Melinda', 'Sy', 'Female', 'melsy147@yahoo.com', 'Manila', 'Philippines'),
(26, 'Emilio', 'Garcia', 'Male', 'emilio_garcia@yahoo.com', 'Manila', 'Philippines'),
(27, 'Mikaela', 'Tolentino', 'Female', 'mikaela.tolentino12@gmail.com', 'Makati', 'Philippines'),
(28, 'Giancarlo', 'Cruz', 'Male', 'gian.cruz@hotmail.com', 'Iloilo City', 'Philippines'),
(29, 'Juliana', 'Ramos', 'Female', 'julianaramos22@gmail.com', 'Pasig', 'Philippines'),
(30, 'Juan', 'Cortez', 'Male', 'cortez_juan@yahoo.com', 'Quezon City', 'Philippines'),
(31, 'Isabella', 'Reyes', 'Female', 'reyes.isabella14@gmail.com', 'Mandaluyong', 'Philippines'),
(32, 'Ricardo', 'Fernandez', 'Male', 'ricardofdz5@gmail.com', 'Pasig', 'Philippines'),
(33, 'Geraldine', 'Dela Cruz', 'Female', 'dela.cruz.geraldine@yahoo.com', 'Taguig', 'Philippines'),
(34, 'Paolo', 'Lopez', 'Male', 'paullopez88@gmail.com', 'Makati', 'Philippines'),
(35, 'Rica', 'Tanchawat', 'Female', 'rtanchawatwork@gmail.com', 'Makati', 'Philippines'),
(36, 'Miguel', 'Gutierrez', 'Male', 'gutierrez.miguel7@hotmail.com', 'Taguig', 'Philippines'),
(37, 'Vanessa', 'Alonzo', 'Female', 'alonzo.vanessa9@gmail.com', 'Naga', 'Philippines'),
(38, 'Felipe', 'Bautista', 'Male', 'felipe_bautista@gmail.com', 'Manila', 'Philippines'),
(39, 'Francesca', 'Santos', 'Female', 'santos_francesca@gmail.com', 'Mandaluyong', 'Philippines'),
(40, 'Nathaniel', 'Santos', 'Male', 'natsantos@yahoo.com', 'Pasig', 'Philippines'),
(41, 'Raquel', 'Gomez', 'Female', 'gomez.raquel7@hotmail.com', 'Naga', 'Philippines'),
(42, 'Eduardo', 'Cruz', 'Male', 'eduardocruz3@gmail.com', 'Iloilo City', 'Philippines'),
(43, 'Jasmin', 'Garcia', 'Female', 'jasmin.garcia11@yahoo.com', 'Pasig', 'Philippines'),
(44, 'Manuel', 'Perez', 'Male', 'perez.manuel4@gmail.com', 'Iloilo City', 'Philippines'),
(45, 'Sofia', 'Dominguez', 'Female', 'dominguez.sofia2@gmail.com', 'San Juan', 'Philippines'),
(46, 'Joaquin', 'Ocampo', 'Male', 'joaq123@hotmail.com', 'Quezon City', 'Philippines'),
(47, 'Jasmin', 'Lacson', 'Female', 'flowergal22@gmail.com', 'Naga', 'Philippines'),
(48, 'Francisco', 'Velasco', 'Male', 'fran_velasco@yahoo.com', 'Taguig', 'Philippines'),
(49, 'Amelia', 'Magno', 'Female', 'ameliamagz81@yahoo.com', 'Pasig', 'Philippines'),
(50, 'Gian', 'Mendoza', 'Male', 'gianmendz@gmail.com', 'Pasig', 'Philippines'),
(51, 'Nadine', 'Santos', 'Female', 'nsantos83@yahoo.com', 'Mandaluyong', 'Philippines'),
(52, 'Sebastian', 'Zamora', 'Male', 'sebbyzam@yahoo.com', 'Makati', 'Philippines'),
(53, 'Rosalie', 'Castillo', 'Female', 'rosaliec_22@gmail.com', 'Makati', 'Philippines'),
(54, 'Zachary', 'Lopez', 'Male', 'zack_lopez96@gmail.com', 'Pasig', 'Philippines'),
(55, 'Susana', 'Floraluna', 'Female', 'sfloraluna888@yahoomail.com', 'San Juan', 'Philippines'),
(56, 'Zane', 'Rivera', 'Non-binary', 'zanerivera99@yahoo.com', 'Quezon City', 'Philippines'),
(57, 'Lara', 'Molina', 'Female', 'larra_mol99@gmail.com', 'Quezon City', 'Philippines'),
(58, 'Nico', 'Garcia', 'Male', 'nico_garcia@hotmail.com', 'Makati', 'Philippines'),
(59, 'Gemma', 'Cruz', 'Female', 'gemcruz84@yahoo.com', 'Quezon City', 'Philippines'),
(60, 'Luigi', 'Reyes', 'Male', 'luigirey24@gmail.com', 'Taguig', 'Philippines'),
(61, 'Roselyn', 'Pascua', 'Female', 'rose_pascua98@gmail.com', 'Naga', 'Philippines'),
(62, 'Cedrick', 'Villanueva', 'Male', 'cedrick_villa88@yahoo.com', 'Naga', 'Philippines'),
(63, 'Angelica', 'Santos', 'Female', 'angelsantos55@gmail.com', 'Quezon City', 'Philippines'),
(64, 'Vince', 'Gonzales', 'Male', 'vince_gonz@yahoo.com', 'San Juan', 'Philippines'),
(65, 'Samantha', 'Bautista', 'Female', 'sambautista22@hotmail.com', 'Makati', 'Philippines'),
(66, 'Ryan', 'Hernandez', 'Male', 'ryanhernz@gmail.com', 'Naga', 'Philippines'),
(67, 'Elaine', 'Cabrera', 'Female', 'elainecabz@yahoo.com', 'San Juan', 'Philippines'),
(68, 'Xander', 'Torres', 'Male', 'xtorres@gmail.com', 'Makati', 'Philippines'),
(69, 'Maximo', 'Garcia', 'Male', 'maximo.garcia@yahoo.com', 'Taguig', 'Philippines'),
(70, 'Emiliano', 'Aguinaldo', 'Male', 'aguiemiliano@hotmail.com', 'Taguig', 'Philippines'),
(71, 'Carmen', 'Lao', 'Female', 'carmenlao@gmail.com', 'Taguig', 'Philippines'),
(72, 'Amado', 'Cruz', 'Male', 'amado.cruz@gmail.com', 'Manila', 'Philippines'),
(73, 'Lorena', 'Co', 'Female', 'renren_love@gmail.com', 'Makati', 'Philippines'),
(74, 'Flordeliza', 'Sanchez', 'Female', 'flosan.chevy@gmail.com', 'Iloilo City', 'Philippines'),
(75, 'Mikko', 'Dela Cruz', 'Male', 'mikkodc@yahoo.com', 'Mandaluyong', 'Philippines'),
(76, 'Catherine', 'Gonzales', 'Female', 'cat.gonzales21@gmail.com', 'Mandaluyong', 'Philippines'),
(77, 'Gregorio', 'Mendoza', 'Male', 'greg.mendoza@yahoo.com', 'Makati', 'Philippines'),
(78, 'Marissa', 'Fernandez', 'Female', 'marissafern@gmail.com', 'Taguig', 'Philippines'),
(79, 'Luis', 'Villanueva', 'Male', 'luisvillanueva@hotmail.com', 'Manila', 'Philippines'),
(80, 'Rebecca', 'Garcia', 'Female', 'rebegarcia07@gmail.com', 'San Juan', 'Philippines'),
(81, 'Paolo', 'Montelibano', 'Male', 'paomontal846@gmail.com', 'Taguig', 'Philippines'),
(82, 'Angelina', 'Galang', 'Female', 'angelgal55@yahoo.com', 'Quezon City', 'Philippines'),
(83, 'Gabriel', 'Salcedo', 'Male', 'gsalcedo67@gmail.com', 'Manila', 'Philippines'),
(84, 'Bianca', 'Chua', 'Female', 'bcchua09@gmail.com', 'Taguig', 'Philippines'),
(85, 'Dennis', 'Uy', 'Male', 'dennisuy123@hotmail.com', 'Taguig', 'Philippines'),
(86, 'Ines', 'Garciano', 'Female', 'idcgarciano@yahoo.com', 'Makati', 'Philippines'),
(87, 'Marlon', 'Cruz', 'Male', 'mcruz222@gmail.com', 'Iloilo City', 'Philippines'),
(88, 'Lara', 'Panganiban', 'Female', 'lpangani321@gmail.com', 'Quezon City', 'Philippines'),
(89, 'Cyrus', 'Reyes', 'Male', 'cyrusreyes87@hotmail.com', 'Mandaluyong', 'Philippines'),
(90, 'Janelle', 'Gonzalez', 'Female', 'jgonzalez542@yahoo.com', 'Iloilo City', 'Philippines'),
(91, 'Francis', 'Caronilo', 'Male', 'cycler_12052001@yahoo.com', 'Makati', 'Philippines'),
(92, 'Mika', 'Avancinco', 'Female', 'avancinco555@gmail.com', 'Quezon City', 'Philippines'),
(93, 'Arnold', 'Gonzales', 'Male', 'arnoldg_84@hotmail.com', 'Quezon City', 'Philippines'),
(94, 'Evelyn', 'Ramos', 'Female', 'eve_ramos02@outlook.com', 'Iloilo City', 'Philippines'),
(95, 'Julius', 'Cruz', 'Male', 'julius_cruz08@gmail.com', 'Mandaluyong', 'Philippines'),
(96, 'Lea', 'Garcia', 'Female', 'lea_garcia05@yahoo.com', 'Taguig', 'Philippines'),
(97, 'Rafael', 'Dominguez', 'Male', 'rafael.dominguez20@gmail.com', 'San Juan', 'Philippines'),
(98, 'Elena', 'Villanueva', 'Female', 'elenav_69@yahoo.com', 'Manila', 'Philippines'),
(99, 'Pedro', 'Santos', 'Male', 'psantos_98@protonmail.com', 'Manila', 'Philippines'),
(100, 'Anna', 'Alvarez', 'Female', 'anna.alvarez93@hotmail.com', 'Naga', 'Philippines');